name: Run Tests

on:
  push:
    branches:
      - main
    # Only watch changes in scripts, json files containing test data and this workflow for push events
    paths: 
      - '**/*.sh'
      - '**/test*.*'
      - '.github/workflows/internal-run-tests.yml'
  pull_request:
    branches:
      - main
    # Only watch changes in scripts, json files containing test data and this workflow for push events
    paths: 
      - '**/*.sh'
      - '**/test*.*'
      - '.github/workflows/internal-run-tests.yml'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GIT Repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
    
    - name: Run script tests
      id: script-tests
      run: ./scripts/runTests.sh