name: Run Tests

on:
  push:
    branches:
      - main
    # Only watch changes in scripts, json files containing test data and this workflow for push events
    paths: 
      - '**/*.sh'
      - '**/test*.*'
      - '.github/workflows/internal-run-tests.yml'
  pull_request:
    branches:
      - main
    # Only watch changes in scripts, json files containing test data and this workflow for push events
    paths: 
      - '**/*.sh'
      - '**/test*.*'
      - '.github/workflows/internal-run-tests.yml'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GIT Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    
    - name: Run script tests
      id: script-tests
      run: ./scripts/runTests.sh